name: copr-build-and-test

on:
  workflow_call:
    inputs:
      ushift-git-url:
        description: "MicroShift git repository URL"
        type: string
        default: "https://github.com/openshift/microshift.git"
      ushift-gitref:
        description: "MicroShift git ref (branch or tag)"
        type: string
        default: "main"
      okd-version-stream:
        description: "OKD x.y stream to build against (e.g. '4.22'). Empty means latest."
        type: string
        default: ""
      copr-repo-name:
        description: "COPR repository name"
        type: string
        required: true
      bootc-image-tag:
        description: "Bootc base image tag"
        type: string
        default: "stream10"

    secrets:
      COPR_CONFIG:
        required: true

env:
  COPR_REPO_NAME: ${{ inputs.copr-repo-name }}

jobs:
  build-dependencies-rpm:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version
        with:
          stream: ${{ inputs.okd-version-stream }}

      - name: Build dependencies RPM
        shell: bash
        env:
          COPR_CONFIG: |
            ${{ secrets.COPR_CONFIG }}
        run: |
          set -euo pipefail
          cd ${GITHUB_WORKSPACE}/
          echo "${COPR_CONFIG}" > /tmp/copr-config

          make copr-dependencies \
            OKD_VERSION_TAG=${{ steps.detect-okd-version.outputs.okd-version-tag }} \
            COPR_REPO_NAME=${{ env.COPR_REPO_NAME }} \
            COPR_CONFIG=/tmp/copr-config

      - name: Build CNI plugins RPM
        shell: bash
        env:
          COPR_CONFIG: |
            ${{ secrets.COPR_CONFIG }}
        run: |
          set -euo pipefail
          cd ${GITHUB_WORKSPACE}/
          echo "${COPR_CONFIG}" > /tmp/copr-config

          make copr-cni \
            COPR_REPO_NAME=${{ env.COPR_REPO_NAME }} \
            COPR_CONFIG=/tmp/copr-config


  build-rpms:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Detect OKD version tag
        id: detect-okd-version
        uses: ./.github/actions/okd-version
        with:
          stream: ${{ inputs.okd-version-stream }}

      - name: Build SRPM
        shell: bash
        env:
          OKD_VERSION_STREAM: ${{ inputs.okd-version-stream }}
        run: |
          cd ${GITHUB_WORKSPACE}/
          make srpm \
            USHIFT_GIT_URL="${{ inputs.ushift-git-url }}" \
            USHIFT_GITREF="${{ inputs.ushift-gitref }}" \
            OKD_VERSION_TAG=${{ steps.detect-okd-version.outputs.okd-version-tag }} \
            OKD_VERSION_STREAM="${OKD_VERSION_STREAM}" \
            SRPM_WORKDIR=/mnt/srpm

      - name: Create copr-cli image and secret
        shell: bash
        env:
          COPR_CONFIG: |
            ${{ secrets.COPR_CONFIG }}
        run: |
          set -euo pipefail
          cd ${GITHUB_WORKSPACE}/
          echo "${COPR_CONFIG}" > /tmp/copr-config
          ls -lah /tmp/copr-config

          make copr-cli

          make copr-cfg-ensure-podman-secret \
            COPR_CONFIG=/tmp/copr-config

      - name: Create COPR build
        shell: bash
        env:
          COPR_CONFIG: |
            ${{ secrets.COPR_CONFIG }}
        run: |
          set -euo pipefail
          cd ${GITHUB_WORKSPACE}/
          echo "${COPR_CONFIG}" > /tmp/copr-config

          make copr-create-build \
            SRPM_WORKDIR=/mnt/srpm \
            COPR_REPO_NAME=${{ env.COPR_REPO_NAME }} \
            COPR_CONFIG=/tmp/copr-config

          make copr-watch-build \
            SRPM_WORKDIR=/mnt/srpm \
            COPR_REPO_NAME=${{ env.COPR_REPO_NAME }}

      - name: Persist version and build ID
        uses: actions/upload-artifact@v4
        with:
          name: srpm-artifacts
          path: |
            /mnt/srpm/version.txt
            /mnt/srpm/build.txt
          overwrite: true


  build-and-test-microshift:
    needs: build-rpms
    strategy:
      matrix:
        runners: [ubuntu-24.04, ubuntu-24.04-arm]
    name: Build RPM images based on COPR build
    runs-on: ${{ matrix.runners }}
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: srpm-artifacts
          path: /tmp/srpm

      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: Prepare the build and run environment
        uses: ./.github/actions/prebuild

      - name: Detect the CPU architecture
        id: detect-cpu-arch
        uses: ./.github/actions/arch

      - name: Create RPMs image with RPMs from COPR
        shell: bash
        run: |
          set -euo pipefail
          cd ${GITHUB_WORKSPACE}/

          make rpm-copr \
            SRPM_WORKDIR=/tmp/srpm \
            RPM_OUTDIR=/mnt/rpms \
            COPR_CHROOT="epel-10-$(uname -m)"

      - name: Run the build action
        uses: ./.github/actions/build
        with:
          ushift-gitref: nil    # RPMs are not built, so no need for git ref or OKD version
          okd-version-tag: nil
          bootc-image-url: quay.io/centos-bootc/centos-bootc
          bootc-image-tag: ${{ inputs.bootc-image-tag }}
          skip-prebuild: "true"
          build: bootc-image

      # Test the local container image with the quick start and clean procedures
      # before releasing the artifacts. Make sure not to run the clean scripts
      # because the images are needed for the release process.
      - name: Run the quick start script and clean scripts
        uses: ./.github/actions/quick-start-clean
        with:
          image-ref: localhost/microshift-okd:latest
          run-clean: false


  regenerate-copr-repo:
    needs: build-and-test-microshift
    runs-on: ubuntu-24.04
    steps:
      - name: Check out MicroShift upstream repository
        uses: actions/checkout@v4

      - name: COPR - Regenerate RPM repo
        shell: bash
        env:
          COPR_CONFIG: |
            ${{ secrets.COPR_CONFIG }}
        run: |
          echo "${COPR_CONFIG}" > /tmp/copr-config
          make copr-regenerate-repos \
            COPR_CONFIG=/tmp/copr-config \
            COPR_REPO_NAME=${{ env.COPR_REPO_NAME }}
